name: Renovate

on:
  schedule:
    - cron: '40 08 * * 1-5'   # Every weekday at 17:00
  workflow_dispatch:        # Manual trigger option

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker availability
        run: |
          docker --version
          docker info

      - uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_LOG_LEVEL: debug
