name: Renovate

on:
  schedule:
    - cron: '0 17 * * 1-5'   # Every weekday at 17:00
  workflow_dispatch:        # Manual trigger option

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
